---

- name: Network Getting Started First Playbook Extended
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: Get facts about device
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Import Device Configs as Code
      include_vars:
        file: config_vars.yml

    - name: Configure Interfaces
      cisco.ios.ios_l3_interfaces:
        config:
        - name: "{{ item }}"
          description: "{{ item.description }}"
          enabled: "{{ item.enable }}"
          ipv4: "{{ item.ipv4.addr }}"
      loop: "{{ devices }}"
          

